baseURL = "https://isaacfreund.com"
languageCode = "en-us"
title = "Isaac Freund"

# Without this hugo sticks a <meta name="generator" content="Hugo 0.87.0" />
# in the output...
disableHugoGeneratorInject = true
